### ISSUE TITLE
Add JavaLand Conference Schedule 

### ISSUE THREAD

**Issue by marcelbirkner** [codecentric/conference-app#1]
- update locations.json with JavaLand locations
- update program.xsl (XlsSessionReader)

**Comment by marcelbirkner** [comment]
Claudia nach Excel Sheet

**Comment by marcelbirkner** [comment]
Claudia nach Excel Sheet Fragen

**Comment by spanneberg** [comment]
Claudia hat uns an Verena weitergeleitet, und die hat sich gemeldet und meinte wir können das als Excel kriegen. Laut DOAG wird sich aber bis kurz davor noch einiges ändern.

Ich hab mal gesagt wir hätten am allerliebsten den aktuellen Stand als Excel und dann kurz vor der Conf den aktualisierten. Wenn das zu viel Aufwand ist dann nur kurz vor der Conf den finalen.
