### ISSUE TITLE
DNS Name - javaland.codecentric.de

### ISSUE THREAD

**Issue by marcelbirkner** [codecentric/conference-app#4]
bei Tobi Knierim?

**Comment by spanneberg** [comment]
Geklärt. Geht. Sobald die EIP da ist werd ich Tobi Bescheid geben und er richtet uns das ein.

**Comment by spanneberg** [comment]
http://osswdev.codecentric.de/ zeigt auf eine instanz mit elastic ip. die würde ich nehmen um auf alles andere zu routen. entweder a la osswdev.codecentric.de/app, osswdev.codecentric.de/ci, ... oder nochmal mit vhosts.
